// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace RentPredictionML.Model
{
    public class ModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("Price"), LoadColumn(1)]
        public float Price { get; set; }


        [ColumnName("UsableSurface"), LoadColumn(2)]
        public float UsableSurface { get; set; }


        [ColumnName("IsArchived"), LoadColumn(3)]
        public bool IsArchived { get; set; }


        [ColumnName("PropertyType"), LoadColumn(4)]
        public string PropertyType { get; set; }


        [ColumnName("StreetName"), LoadColumn(5)]
        public string StreetName { get; set; }


        [ColumnName("Floor"), LoadColumn(6)]
        public string Floor { get; set; }


        [ColumnName("HasBalcony"), LoadColumn(7)]
        public bool HasBalcony { get; set; }


        [ColumnName("HasParking"), LoadColumn(8)]
        public bool HasParking { get; set; }


        [ColumnName("HasGarden"), LoadColumn(9)]
        public bool HasGarden { get; set; }


        [ColumnName("HasHeating"), LoadColumn(10)]
        public bool HasHeating { get; set; }


        [ColumnName("IsForSale"), LoadColumn(11)]
        public bool IsForSale { get; set; }


        [ColumnName("NumberOfRooms"), LoadColumn(12)]
        public float NumberOfRooms { get; set; }


        [ColumnName("NumberOfBaths"), LoadColumn(13)]
        public float NumberOfBaths { get; set; }


        [ColumnName("NumberOfBalconies"), LoadColumn(14)]
        public float NumberOfBalconies { get; set; }


        [ColumnName("NumberOfParkingSpots"), LoadColumn(15)]
        public float NumberOfParkingSpots { get; set; }


        [ColumnName("BuildingSeniority"), LoadColumn(16)]
        public string BuildingSeniority { get; set; }


        [ColumnName("BuildingType"), LoadColumn(17)]
        public string BuildingType { get; set; }


        [ColumnName("Endowment"), LoadColumn(18)]
        public string Endowment { get; set; }


        [ColumnName("Finish"), LoadColumn(19)]
        public string Finish { get; set; }


        [ColumnName("Partitioning"), LoadColumn(20)]
        public string Partitioning { get; set; }


    }
}
